stages:
  data_ingestion:
    cmd: python data_ingestion.py
    outs:
      - data/raw_data.csv

  data_preprocessing:
    cmd: python data_preprocessing.py
    deps:
      - data/raw_data.csv
    outs:
      - data/clean_data.csv

  feature_engineering:
    cmd: python feature_engineering.py
    deps:
      - data/clean_data.csv
    outs:
      - data/features.csv

  model_building:
    cmd: python model_building.py
    deps:
      - data/features.csv
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python mode_evaluation.py
    deps:
      - models/model.pkl
      - data/features.csv
    outs:
      - reports/metrics.json
